name       : libnfsidmap
version    : 0.27
release    : 2
source     :
    - https://fedorapeople.org/~steved/libnfsidmap/0.27/libnfsidmap-0.27.tar.gz : 9c5916b644b85c6f5e4e1bdd0d23caa6c956ee742b5a27be6a618311a924ef8e
license    : BSD-3-Clause
component  : network.utils
summary    : NFS ID Mapping he libnfsidmap package contains a library to help mapping id's, mainly for NFSv4.
description: |
    The libnfsidmap package contains a library to help mapping id's, mainly for NFSv4.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
