name       : libnfsidmap
version    : 0.26
release    : 1
source     :
    - https://fedorapeople.org/~steved/libnfsidmap/0.26/libnfsidmap-0.26.tar.bz2 : 391cd35a8aa48bcba1678b483c3e2525d0990eca963bb035962fcf1e3ee2a8bf
license    : BSD-3-Clause
component  : network.utils
summary    : NFS ID Mapping he libnfsidmap package contains a library to help mapping id's, mainly for NFSv4.
description: |
    The libnfsidmap package contains a library to help mapping id's, mainly for NFSv4.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
